services:
  - type: web
    name: ai-financial-bot
    env: python
    buildCommand: chmod +x ./build.sh && ./build.sh
    startCommand: python start.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: GOOGLE_CREDENTIALS_FILE
        sync: false
      - key: SPREADSHEET_ID
        sync: false
      - key: DRIVE_FOLDER_ID
        sync: false 
